#!/usr/bin/python

name = raw_input("What is your name?")
print "Your name is "+name

if name == "seba":
    print "You are seba"
    print "The computer admin"
elif name =="john":
    print "You are JOhn"
    print "Regular User"
else:
    print "Unknown user"


